# Generated by Django 5.2.7 on 2026-03-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu_menutranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Key'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='MenuTranslation',
        ),
    ]
